### ISSUE TITLE
single-file hangs in docker node:alpine

### ISSUE THREAD

**Issue by faridanthony** [gildas-lormeau/single-file-cli#105]
Hello, thank you for the amazing lib! I'm trying to get it running within a docker container but the command seems to hang indefinitely without and output or error.

single-file "https://www.wikipedia.org" 7cd1037d-8066-45b8-83cd-05384b1caa06.html --browser-executable-path=/usr/bin/chromium --browser-args=[\"--headless=new\",\"--no-sandbox\",\"--no-zygote\",\"--disable-dev-shm-usage\",\"--disable-software-rasterizer\",\"--run-all-compositor-stages-before-draw\",\"--hide-scrollbars\",\"--autoplay-policy=no-user-gesture-required\",\"--no-first-run\",\"--use-fake-ui-for-media-stream\",\"--use-fake-device-for-media-stream\",\"--disable-sync\",\"--window-size=1440,2000\"]

I'm not sure how to debug this. Any help would be greatly appreciated.

**Comment by faridanthony** [comment]
This might actually be due to docker/mac. Please close.

**Comment by gildas-lormeau** [comment]
No problem ;)

**Comment by jburns24** [comment]
> This might actually be due to docker/mac. Closing the issue until I have more details.

Experiencing similar behavior running singlefile on a macbook. Any follow up on what worked here?

**Comment by jburns24** [comment]
In case others come across this issue. My issue turned out to be related to the sites I was backing up.

`➜  single-file-cli git:(master) ✗ docker run -v $(pwd):/usr/src/app/out single-file-cli "https://www.eatthis.com/cauliflower-nachos-recipe" cauliflower-nachos-recipe.html`

This would always hang for me

`➜  single-file-cli git:(master) ✗ docker run -v $(pwd):/usr/src/app/out single-file-cli "https://www.wikipedia.org" wikipedia.html`

Would work. 

I tried some of the --browser-wait-until options but couldn't figure it out. 

The compiled binary was working locally 

`➜  single-file-cli git:(master) ✗ ./single-file "https://www.eatthis.com/cauliflower-nachos-recipe" "./out/cauliflower-nachos-recipe.html" --dump-content` 

So seems the problem is somehow related to the docker environment (currently testing on Docker version 28.0.4, build b8034c0)
