### ISSUE TITLE
Adding an option for printing the page to PDF

### ISSUE THREAD

**Issue by VAdri** [gildas-lormeau/single-file-cli#121]
I use `single-file-cli` with the options `--embed-screenshot` and `--compress-content` in order to have several formats of my page. I then create symlinks with a `.zip` and `.png` extensions, so it's very convenient to open the file with the program I need:

```sh
single-file https://www.wikipedia.org \
            ./wikipedia.html   \
            --compress-content \
            --embed-screenshot \
    && ln -s ./wikipedia.html ./wikipedia.zip \
    && ln -s ./wikipedia.html ./wikipedia.png
```

I would like to do the same with PDF files because they can have a better layout for reading on some devices.

I know that the Chrome DevTools Protocol has an API for [Page.printToPDF](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF), so I guess there would not be too much difficulties on that side, but I'm not sure if the trick with the self-extracting archive file would work with an additional format. Alternatively, would it be possible to simply dump everything in a regular ZIP file?

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. I was not aware of the existence of `Page.printToPDF` and I must admit it was very tempting to implement this feature. The new option `--embed-pdf` will be available in the next version. From a technical point of view, the PDF data is stored in a HTML node instead of the ZIP file though.
